name: myaac

services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ..:/var/www/html
      - ${CANARY_PATH}:/srv/canary:ro
    networks:
      - myaac-net
      - canary-net

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '${MYAAC_PORT}:80'
    volumes:
      - ..:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - myaac-net
      - proxy-net

networks:
  myaac-net:
    driver: bridge
  canary-net:
    external: true
    name: otbr_canary-net
  proxy-net:
    external: true
    name: tunnel-test_default
