server {
    listen 80;
    root /var/www/html;
    index index.php;
    server_name _;

    client_max_body_size 10M;

    # block access to system internals
    location ~ /system {
        deny all;
    }

    # block sensitive file types
    location ~\.(ht|md|json|dist|sql)$ {
        deny all;
    }

    # block git files
    location ~ /\.git {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 240;
    }
}
